// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooDAL;

#nullable disable

namespace ZooDAL.Migrations
{
    [DbContext(typeof(ZooDbContext))]
    partial class ZooDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZooDAL.Entities.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e996328-3381-4409-b23d-7196209012fe"),
                            Age = 2,
                            CategoryID = new Guid("33d69f6a-2a30-4955-81b3-d849aff528e2"),
                            Description = "Penguin description",
                            ImagePath = "10b02f99-82cb-45a2-9f6f-9ff5b93aecfa.jpg",
                            Name = "Penguin"
                        },
                        new
                        {
                            Id = new Guid("fd1caf0a-8a78-4632-86b3-9eaff1a8dddf"),
                            Age = 5,
                            CategoryID = new Guid("33d69f6a-2a30-4955-81b3-d849aff528e2"),
                            Description = "Parrot description",
                            ImagePath = "9a711fee-6d32-4ed0-b1d6-a5f4958d2208.jpg",
                            Name = "Parrot"
                        },
                        new
                        {
                            Id = new Guid("85350b43-d2a7-4caa-9669-c5d75b721f43"),
                            Age = 3,
                            CategoryID = new Guid("33d69f6a-2a30-4955-81b3-d849aff528e2"),
                            Description = "Eagle description",
                            ImagePath = "4eb9ea13-b0c3-4144-be0c-0d1eff68aa7b.jpg",
                            Name = "Eagle"
                        },
                        new
                        {
                            Id = new Guid("5719bf16-429e-4b19-bcd3-8cb6656a44c0"),
                            Age = 8,
                            CategoryID = new Guid("40f01712-a3f6-482a-ac23-d8f3940678bb"),
                            Description = "Chimpanzee description",
                            ImagePath = "475027aa-44ba-4ce3-8a75-b3c261599b0d.jpg",
                            Name = "Chimpanzee"
                        },
                        new
                        {
                            Id = new Guid("34ec3b43-b086-4004-a5c3-d3e072ff4e0a"),
                            Age = 12,
                            CategoryID = new Guid("40f01712-a3f6-482a-ac23-d8f3940678bb"),
                            Description = "Gorilla description",
                            ImagePath = "7741d954-515d-4222-a66b-d8f23273ea2c.jpg",
                            Name = "Gorilla"
                        },
                        new
                        {
                            Id = new Guid("36f30705-b073-479e-a238-2f8c9761fb2e"),
                            Age = 10,
                            CategoryID = new Guid("40f01712-a3f6-482a-ac23-d8f3940678bb"),
                            Description = "Orangutan description",
                            ImagePath = "0ed86487-a07f-4c21-8fb8-3751215bef68.jpg",
                            Name = "Orangutan"
                        },
                        new
                        {
                            Id = new Guid("8c3103bf-3cfc-49b2-9b78-1aa9f2b5aea1"),
                            Age = 4,
                            CategoryID = new Guid("d9ccbfd0-5847-4c10-bec1-5f8ae48d5a77"),
                            Description = "Lion description",
                            ImagePath = "2021be47-0f90-4053-bb1a-d939bde5bc7f.jpg",
                            Name = "Lion"
                        },
                        new
                        {
                            Id = new Guid("0dbeb006-d74c-4bfd-90ea-48ecd6b5ceb0"),
                            Age = 6,
                            CategoryID = new Guid("d9ccbfd0-5847-4c10-bec1-5f8ae48d5a77"),
                            Description = "Cheetah description",
                            ImagePath = "433a2c09-520b-48c1-a7bc-1e6b9c62ba12.jpg",
                            Name = "Cheetah"
                        },
                        new
                        {
                            Id = new Guid("cd84bd40-9bbb-4268-8c5c-ce13a72e2cff"),
                            Age = 7,
                            CategoryID = new Guid("d9ccbfd0-5847-4c10-bec1-5f8ae48d5a77"),
                            Description = "Tiger description",
                            ImagePath = "d15b6b92-391b-43ea-a55f-31e8f4cd163f.jpg",
                            Name = "Tiger"
                        });
                });

            modelBuilder.Entity("ZooDAL.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33d69f6a-2a30-4955-81b3-d849aff528e2"),
                            Name = "Birds"
                        },
                        new
                        {
                            Id = new Guid("40f01712-a3f6-482a-ac23-d8f3940678bb"),
                            Name = "Monkeys"
                        },
                        new
                        {
                            Id = new Guid("d9ccbfd0-5847-4c10-bec1-5f8ae48d5a77"),
                            Name = "Cats"
                        });
                });

            modelBuilder.Entity("ZooDAL.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimalID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalID");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14ce98f9-70bf-4601-b881-b0ac5386d01d"),
                            AnimalID = new Guid("8c3103bf-3cfc-49b2-9b78-1aa9f2b5aea1"),
                            Content = "This lion is amazing!"
                        },
                        new
                        {
                            Id = new Guid("1d350238-43e6-4032-85ba-507ec622ac9d"),
                            AnimalID = new Guid("8c3103bf-3cfc-49b2-9b78-1aa9f2b5aea1"),
                            Content = "The lion's majestic beauty is breathtaking!"
                        },
                        new
                        {
                            Id = new Guid("f52937b1-533b-4f5b-a9d2-f79dfbc8f463"),
                            AnimalID = new Guid("8c3103bf-3cfc-49b2-9b78-1aa9f2b5aea1"),
                            Content = "I'm in awe of this incredible lion!"
                        },
                        new
                        {
                            Id = new Guid("1d3a5e5d-aaa8-43ef-809b-a53b1c9c691f"),
                            AnimalID = new Guid("85350b43-d2a7-4caa-9669-c5d75b721f43"),
                            Content = "The eagle is soaring through the sky with grace!"
                        },
                        new
                        {
                            Id = new Guid("0de264fc-ad18-4dfe-b315-cc6ae8231012"),
                            AnimalID = new Guid("5e996328-3381-4409-b23d-7196209012fe"),
                            Content = "The penguin waddles with cuteness!"
                        },
                        new
                        {
                            Id = new Guid("17d73aaf-314d-4396-a8cf-777dbafafbed"),
                            AnimalID = new Guid("5e996328-3381-4409-b23d-7196209012fe"),
                            Content = "The penguin's sleek feathers are mesmerizing!"
                        },
                        new
                        {
                            Id = new Guid("593568f8-3865-47a0-a241-b95cdf19d944"),
                            AnimalID = new Guid("34ec3b43-b086-4004-a5c3-d3e072ff4e0a"),
                            Content = "The gorilla's strength is awe-inspiring!"
                        },
                        new
                        {
                            Id = new Guid("2bbaed1f-9090-40d7-85cf-9db04635c7e3"),
                            AnimalID = new Guid("34ec3b43-b086-4004-a5c3-d3e072ff4e0a"),
                            Content = "The gorilla's intelligence shines through!"
                        },
                        new
                        {
                            Id = new Guid("44230bb6-9718-43bd-a254-21c1e34c125a"),
                            AnimalID = new Guid("34ec3b43-b086-4004-a5c3-d3e072ff4e0a"),
                            Content = "The gorilla's gentle nature is heartwarming!"
                        },
                        new
                        {
                            Id = new Guid("7db87dcc-c4a5-4e6c-ace5-f10afc3eae48"),
                            AnimalID = new Guid("34ec3b43-b086-4004-a5c3-d3e072ff4e0a"),
                            Content = "The gorilla's interactions with its family are fascinating!"
                        },
                        new
                        {
                            Id = new Guid("73703a8a-98a9-4495-9b8f-dfa539a5ca0a"),
                            AnimalID = new Guid("34ec3b43-b086-4004-a5c3-d3e072ff4e0a"),
                            Content = "The gorilla's expressive eyes captivate everyone!"
                        });
                });

            modelBuilder.Entity("ZooDAL.Entities.Animal", b =>
                {
                    b.HasOne("ZooDAL.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ZooDAL.Entities.Comment", b =>
                {
                    b.HasOne("ZooDAL.Entities.Animal", "Animal")
                        .WithMany("Comments")
                        .HasForeignKey("AnimalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("ZooDAL.Entities.Animal", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
